### ISSUE TITLE
Seperate kernel- and application-logic

### ISSUE THREAD

**Issue by sebkpp** [tterpi/VRSketchingGeometry#1]
Since the kernel will be used in many projects it would be better to isolate the actual kernel and put it into the plugins-folder. I suggest something like this:

Assets
->Plugins
->->VRSketchingGeometry
->->->Scripts
->->->Prefabs
->->->Shaders
->->->Examples
->->->....

**Comment by tterpi** [comment]
I moved the scripts to the Plugins folder as suggested. I also introduced a VRSketchingGeometry namespace to seperate the scripts from the rest of the applications code. This is on master.
